### ISSUE TITLE
Error message should be amended if page was unpublished

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#2]
Hello,

If you set the FB page you wish to stream and this page was unpublished the following error message is displayed: 

Critical Error: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

![unpublishpage](https://cloud.githubusercontent.com/assets/8656805/7409893/0531ef00-ef22-11e4-86e3-11b69bf2bf46.png)

Please amend the error message so it is user-friendly. I have attached an example of error message design we have across the system:

![exampleerrormessage](https://cloud.githubusercontent.com/assets/8656805/7410079/a2dddd80-ef23-11e4-9ee2-d316298aa7de.png)

Let me know if you have any questions.

**Comment by LaboratoryGA** [comment]
I can wrap the error is the alert box, but I cannot change the actual wording of the message. The wording comes directly from FB site/API and doesn't provide an "error code" to identify what the problem is (generically). There is also no clear indication of WHY the request is unsupported, so there really is no way to change that particular wording.

**Comment by LaboratoryGA** [comment]
As with #4 this will never actually be visible once the final version is released, as directly querying the streams will happen as a background process.
