### ISSUE TITLE
Limit the stream to display is not working on my side

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/socialfeed#8]
Hello,

I have limited the stream to display, however still both Twitter and FB posts are displaying, when I limited it to FB only.

I have used the following code:

<component class="SocialComponent" social_filter="fb">

Please let me know if I'm missing something.

**Comment by olganovosad** [comment]
this is working, pasted wrong code

**Comment by LaboratoryGA** [comment]
Unable to reproduce. If I remove "twitter" from the selection, Twitter no longer shows. Can you please supply the component code you are using?

**Comment by olganovosad** [comment]
hello,

Sorry, for some reason the code is not visible when I save the ticket (I removed <> so the code doesn't disappear)

I'm using this code:

component class="SocialComponent" social_filter="fb"

I, also, tried: 

component class="SocialComponent" social_filter="facebook"

When I save it and refresh the page, the Twitter posts are still visible on my side.

**Comment by LaboratoryGA** [comment]
I've retested this, and simply cannot duplicate the problem. If I remove "twitter" from the source_filter, then it (correctly) removes the Twitter feed. I'm going to close this for now - if you still experience it, I may need access to the test site on which this is installed, because it's simply not happening on the server I use. Please post a new issue under the other project if it persists.
